### PR TITLE
[travis] Add Travis File.

### PR DESCRIPTION
**Pull request by ejgallego**
We only test dev for master.

### CODE REVIEW

**Comment by ejgallego** [comment]
@ybertot can you enable Travis for this repos at https://travis-ci.org/ybertot/plugin_tutorials so we can see if the CI works?

**Comment by ejgallego** [comment]
A build on my repos is here: https://travis-ci.org/ejgallego/plugin_tutorials/builds/451326533

**Comment by ejgallego** [comment]
Successful build here https://travis-ci.org/ejgallego/plugin_tutorials/builds/451341443 !

**Comment by ybertot** [comment]
Thanks!

**Comment by ejgallego** [comment]
Thanks to you!

**Pull request merged**
